// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// median_bandwidth_cpp
double median_bandwidth_cpp(NumericMatrix x);
RcppExport SEXP _dda_median_bandwidth_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(median_bandwidth_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// build_kernel_matrix_cpp
NumericMatrix build_kernel_matrix_cpp(NumericMatrix x, std::string kernel, double bandwidth, int degree, double coef0);
RcppExport SEXP _dda_build_kernel_matrix_cpp(SEXP xSEXP, SEXP kernelSEXP, SEXP bandwidthSEXP, SEXP degreeSEXP, SEXP coef0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    rcpp_result_gen = Rcpp::wrap(build_kernel_matrix_cpp(x, kernel, bandwidth, degree, coef0));
    return rcpp_result_gen;
END_RCPP
}
// center_kernel_cpp
NumericMatrix center_kernel_cpp(NumericMatrix K);
RcppExport SEXP _dda_center_kernel_cpp(SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(center_kernel_cpp(K));
    return rcpp_result_gen;
END_RCPP
}
// hsic_trace_cpp
double hsic_trace_cpp(NumericMatrix Kx_c, NumericMatrix Ky_c);
RcppExport SEXP _dda_hsic_trace_cpp(SEXP Kx_cSEXP, SEXP Ky_cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Kx_c(Kx_cSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ky_c(Ky_cSEXP);
    rcpp_result_gen = Rcpp::wrap(hsic_trace_cpp(Kx_c, Ky_c));
    return rcpp_result_gen;
END_RCPP
}
// permute_hsic_cpp
NumericVector permute_hsic_cpp(NumericMatrix Kx_c, NumericMatrix Ky_c, int B);
RcppExport SEXP _dda_permute_hsic_cpp(SEXP Kx_cSEXP, SEXP Ky_cSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Kx_c(Kx_cSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ky_c(Ky_cSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(permute_hsic_cpp(Kx_c, Ky_c, B));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_hsic_cpp
NumericVector bootstrap_hsic_cpp(NumericMatrix Kx, NumericMatrix Ky, int B);
RcppExport SEXP _dda_bootstrap_hsic_cpp(SEXP KxSEXP, SEXP KySEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ky(KySEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_hsic_cpp(Kx, Ky, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dda_median_bandwidth_cpp", (DL_FUNC) &_dda_median_bandwidth_cpp, 1},
    {"_dda_build_kernel_matrix_cpp", (DL_FUNC) &_dda_build_kernel_matrix_cpp, 5},
    {"_dda_center_kernel_cpp", (DL_FUNC) &_dda_center_kernel_cpp, 1},
    {"_dda_hsic_trace_cpp", (DL_FUNC) &_dda_hsic_trace_cpp, 2},
    {"_dda_permute_hsic_cpp", (DL_FUNC) &_dda_permute_hsic_cpp, 3},
    {"_dda_bootstrap_hsic_cpp", (DL_FUNC) &_dda_bootstrap_hsic_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dda(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
