# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

median_bandwidth_cpp <- function(x) {
    .Call(`_dda_median_bandwidth_cpp`, x)
}

build_kernel_matrix_cpp <- function(x, kernel, bandwidth, degree, coef0) {
    .Call(`_dda_build_kernel_matrix_cpp`, x, kernel, bandwidth, degree, coef0)
}

center_kernel_cpp <- function(K) {
    .Call(`_dda_center_kernel_cpp`, K)
}

hsic_trace_cpp <- function(Kx_c, Ky_c) {
    .Call(`_dda_hsic_trace_cpp`, Kx_c, Ky_c)
}

permute_hsic_cpp <- function(Kx_c, Ky_c, B) {
    .Call(`_dda_permute_hsic_cpp`, Kx_c, Ky_c, B)
}

bootstrap_hsic_cpp <- function(Kx, Ky, B) {
    .Call(`_dda_bootstrap_hsic_cpp`, Kx, Ky, B)
}

